### ISSUE TITLE
Tag 'p strong' missing backup font-families

### ISSUE THREAD

**Issue by matthew-dailey** [tnguyen/blueface#1]
Using the blueface theme, I added a `<strong>` section that looked fine with `jekyll serve`, but on GitHub Pages the strong font switched to some serif font, probably because the Roboto font was not found.

I can make a PR to add backup font-families to the `p strong` tag (which fixed my issue).

**Comment by thien** [comment]
Sure, make a PR and i'll merge it with the master branch. Thanks!
